namespace myBOOK.data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Composkeys : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Favourites", "Book_ID", "dbo.Books");
            DropForeignKey("dbo.FutureReadBooks", "Book_ID", "dbo.Books");
            DropForeignKey("dbo.PastReadBooks", "Book_ID", "dbo.Books");
            DropForeignKey("dbo.Reviews", "Book_ID", "dbo.Books");
            DropForeignKey("dbo.Scores", "Book_ID", "dbo.Books");
            DropForeignKey("dbo.Favourites", "User_ID", "dbo.Users");
            DropForeignKey("dbo.FutureReadBooks", "User_ID", "dbo.Users");
            DropForeignKey("dbo.PastReadBooks", "User_ID", "dbo.Users");
            DropForeignKey("dbo.Reviews", "User_ID", "dbo.Users");
            DropForeignKey("dbo.Scores", "User_ID", "dbo.Users");
            DropIndex("dbo.Favourites", new[] { "Book_ID" });
            DropIndex("dbo.Favourites", new[] { "User_ID" });
            DropIndex("dbo.FutureReadBooks", new[] { "Book_ID" });
            DropIndex("dbo.FutureReadBooks", new[] { "User_ID" });
            DropIndex("dbo.PastReadBooks", new[] { "Book_ID" });
            DropIndex("dbo.PastReadBooks", new[] { "User_ID" });
            DropIndex("dbo.Reviews", new[] { "Book_ID" });
            DropIndex("dbo.Reviews", new[] { "User_ID" });
            DropIndex("dbo.Scores", new[] { "Book_ID" });
            DropIndex("dbo.Scores", new[] { "User_ID" });
            RenameColumn(table: "dbo.Favourites", name: "Book_ID", newName: "Book_BookName");
            RenameColumn(table: "dbo.Favourites", name: "User_ID", newName: "User_Login");
            RenameColumn(table: "dbo.FutureReadBooks", name: "Book_ID", newName: "Book_BookName");
            RenameColumn(table: "dbo.FutureReadBooks", name: "User_ID", newName: "User_Login");
            RenameColumn(table: "dbo.PastReadBooks", name: "Book_ID", newName: "Book_BookName");
            RenameColumn(table: "dbo.PastReadBooks", name: "User_ID", newName: "User_Login");
            RenameColumn(table: "dbo.Reviews", name: "Book_ID", newName: "Book_BookName");
            RenameColumn(table: "dbo.Reviews", name: "User_ID", newName: "User_Login");
            RenameColumn(table: "dbo.Scores", name: "Book_ID", newName: "Book_BookName");
            RenameColumn(table: "dbo.Scores", name: "User_ID", newName: "User_Login");
            DropPrimaryKey("dbo.Books");
            DropPrimaryKey("dbo.Users");
            AddColumn("dbo.Favourites", "Book_Author", c => c.String(maxLength: 128));
            AddColumn("dbo.FutureReadBooks", "Book_Author", c => c.String(maxLength: 128));
            AddColumn("dbo.PastReadBooks", "Book_Author", c => c.String(maxLength: 128));
            AddColumn("dbo.Reviews", "Book_Author", c => c.String(maxLength: 128));
            AddColumn("dbo.Scores", "Book_Author", c => c.String(maxLength: 128));
            AlterColumn("dbo.Books", "BookName", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Books", "Author", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Favourites", "Book_BookName", c => c.String(maxLength: 128));
            AlterColumn("dbo.Favourites", "User_Login", c => c.String(maxLength: 128));
            AlterColumn("dbo.Users", "Login", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.FutureReadBooks", "Book_BookName", c => c.String(maxLength: 128));
            AlterColumn("dbo.FutureReadBooks", "User_Login", c => c.String(maxLength: 128));
            AlterColumn("dbo.PastReadBooks", "Book_BookName", c => c.String(maxLength: 128));
            AlterColumn("dbo.PastReadBooks", "User_Login", c => c.String(maxLength: 128));
            AlterColumn("dbo.Reviews", "Book_BookName", c => c.String(maxLength: 128));
            AlterColumn("dbo.Reviews", "User_Login", c => c.String(maxLength: 128));
            AlterColumn("dbo.Scores", "Book_BookName", c => c.String(maxLength: 128));
            AlterColumn("dbo.Scores", "User_Login", c => c.String(maxLength: 128));
            AddPrimaryKey("dbo.Books", new[] { "BookName", "Author" });
            AddPrimaryKey("dbo.Users", "Login");
            CreateIndex("dbo.Favourites", new[] { "Book_BookName", "Book_Author" });
            CreateIndex("dbo.Favourites", "User_Login");
            CreateIndex("dbo.FutureReadBooks", new[] { "Book_BookName", "Book_Author" });
            CreateIndex("dbo.FutureReadBooks", "User_Login");
            CreateIndex("dbo.PastReadBooks", new[] { "Book_BookName", "Book_Author" });
            CreateIndex("dbo.PastReadBooks", "User_Login");
            CreateIndex("dbo.Reviews", new[] { "Book_BookName", "Book_Author" });
            CreateIndex("dbo.Reviews", "User_Login");
            CreateIndex("dbo.Scores", new[] { "Book_BookName", "Book_Author" });
            CreateIndex("dbo.Scores", "User_Login");
            AddForeignKey("dbo.Favourites", new[] { "Book_BookName", "Book_Author" }, "dbo.Books", new[] { "BookName", "Author" });
            AddForeignKey("dbo.FutureReadBooks", new[] { "Book_BookName", "Book_Author" }, "dbo.Books", new[] { "BookName", "Author" });
            AddForeignKey("dbo.PastReadBooks", new[] { "Book_BookName", "Book_Author" }, "dbo.Books", new[] { "BookName", "Author" });
            AddForeignKey("dbo.Reviews", new[] { "Book_BookName", "Book_Author" }, "dbo.Books", new[] { "BookName", "Author" });
            AddForeignKey("dbo.Scores", new[] { "Book_BookName", "Book_Author" }, "dbo.Books", new[] { "BookName", "Author" });
            AddForeignKey("dbo.Favourites", "User_Login", "dbo.Users", "Login");
            AddForeignKey("dbo.FutureReadBooks", "User_Login", "dbo.Users", "Login");
            AddForeignKey("dbo.PastReadBooks", "User_Login", "dbo.Users", "Login");
            AddForeignKey("dbo.Reviews", "User_Login", "dbo.Users", "Login");
            AddForeignKey("dbo.Scores", "User_Login", "dbo.Users", "Login");
            DropColumn("dbo.Books", "ID");
            DropColumn("dbo.Users", "ID");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Users", "ID", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Books", "ID", c => c.Int(nullable: false, identity: true));
            DropForeignKey("dbo.Scores", "User_Login", "dbo.Users");
            DropForeignKey("dbo.Reviews", "User_Login", "dbo.Users");
            DropForeignKey("dbo.PastReadBooks", "User_Login", "dbo.Users");
            DropForeignKey("dbo.FutureReadBooks", "User_Login", "dbo.Users");
            DropForeignKey("dbo.Favourites", "User_Login", "dbo.Users");
            DropForeignKey("dbo.Scores", new[] { "Book_BookName", "Book_Author" }, "dbo.Books");
            DropForeignKey("dbo.Reviews", new[] { "Book_BookName", "Book_Author" }, "dbo.Books");
            DropForeignKey("dbo.PastReadBooks", new[] { "Book_BookName", "Book_Author" }, "dbo.Books");
            DropForeignKey("dbo.FutureReadBooks", new[] { "Book_BookName", "Book_Author" }, "dbo.Books");
            DropForeignKey("dbo.Favourites", new[] { "Book_BookName", "Book_Author" }, "dbo.Books");
            DropIndex("dbo.Scores", new[] { "User_Login" });
            DropIndex("dbo.Scores", new[] { "Book_BookName", "Book_Author" });
            DropIndex("dbo.Reviews", new[] { "User_Login" });
            DropIndex("dbo.Reviews", new[] { "Book_BookName", "Book_Author" });
            DropIndex("dbo.PastReadBooks", new[] { "User_Login" });
            DropIndex("dbo.PastReadBooks", new[] { "Book_BookName", "Book_Author" });
            DropIndex("dbo.FutureReadBooks", new[] { "User_Login" });
            DropIndex("dbo.FutureReadBooks", new[] { "Book_BookName", "Book_Author" });
            DropIndex("dbo.Favourites", new[] { "User_Login" });
            DropIndex("dbo.Favourites", new[] { "Book_BookName", "Book_Author" });
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Books");
            AlterColumn("dbo.Scores", "User_Login", c => c.Int());
            AlterColumn("dbo.Scores", "Book_BookName", c => c.Int());
            AlterColumn("dbo.Reviews", "User_Login", c => c.Int());
            AlterColumn("dbo.Reviews", "Book_BookName", c => c.Int());
            AlterColumn("dbo.PastReadBooks", "User_Login", c => c.Int());
            AlterColumn("dbo.PastReadBooks", "Book_BookName", c => c.Int());
            AlterColumn("dbo.FutureReadBooks", "User_Login", c => c.Int());
            AlterColumn("dbo.FutureReadBooks", "Book_BookName", c => c.Int());
            AlterColumn("dbo.Users", "Login", c => c.String());
            AlterColumn("dbo.Favourites", "User_Login", c => c.Int());
            AlterColumn("dbo.Favourites", "Book_BookName", c => c.Int());
            AlterColumn("dbo.Books", "Author", c => c.String());
            AlterColumn("dbo.Books", "BookName", c => c.String());
            DropColumn("dbo.Scores", "Book_Author");
            DropColumn("dbo.Reviews", "Book_Author");
            DropColumn("dbo.PastReadBooks", "Book_Author");
            DropColumn("dbo.FutureReadBooks", "Book_Author");
            DropColumn("dbo.Favourites", "Book_Author");
            AddPrimaryKey("dbo.Users", "ID");
            AddPrimaryKey("dbo.Books", "ID");
            RenameColumn(table: "dbo.Scores", name: "User_Login", newName: "User_ID");
            RenameColumn(table: "dbo.Scores", name: "Book_BookName", newName: "Book_ID");
            RenameColumn(table: "dbo.Reviews", name: "User_Login", newName: "User_ID");
            RenameColumn(table: "dbo.Reviews", name: "Book_BookName", newName: "Book_ID");
            RenameColumn(table: "dbo.PastReadBooks", name: "User_Login", newName: "User_ID");
            RenameColumn(table: "dbo.PastReadBooks", name: "Book_BookName", newName: "Book_ID");
            RenameColumn(table: "dbo.FutureReadBooks", name: "User_Login", newName: "User_ID");
            RenameColumn(table: "dbo.FutureReadBooks", name: "Book_BookName", newName: "Book_ID");
            RenameColumn(table: "dbo.Favourites", name: "User_Login", newName: "User_ID");
            RenameColumn(table: "dbo.Favourites", name: "Book_BookName", newName: "Book_ID");
            CreateIndex("dbo.Scores", "User_ID");
            CreateIndex("dbo.Scores", "Book_ID");
            CreateIndex("dbo.Reviews", "User_ID");
            CreateIndex("dbo.Reviews", "Book_ID");
            CreateIndex("dbo.PastReadBooks", "User_ID");
            CreateIndex("dbo.PastReadBooks", "Book_ID");
            CreateIndex("dbo.FutureReadBooks", "User_ID");
            CreateIndex("dbo.FutureReadBooks", "Book_ID");
            CreateIndex("dbo.Favourites", "User_ID");
            CreateIndex("dbo.Favourites", "Book_ID");
            AddForeignKey("dbo.Scores", "User_ID", "dbo.Users", "ID");
            AddForeignKey("dbo.Reviews", "User_ID", "dbo.Users", "ID");
            AddForeignKey("dbo.PastReadBooks", "User_ID", "dbo.Users", "ID");
            AddForeignKey("dbo.FutureReadBooks", "User_ID", "dbo.Users", "ID");
            AddForeignKey("dbo.Favourites", "User_ID", "dbo.Users", "ID");
            AddForeignKey("dbo.Scores", "Book_ID", "dbo.Books", "ID");
            AddForeignKey("dbo.Reviews", "Book_ID", "dbo.Books", "ID");
            AddForeignKey("dbo.PastReadBooks", "Book_ID", "dbo.Books", "ID");
            AddForeignKey("dbo.FutureReadBooks", "Book_ID", "dbo.Books", "ID");
            AddForeignKey("dbo.Favourites", "Book_ID", "dbo.Books", "ID");
        }
    }
}
