// <auto-generated />
namespace myBOOK.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Composkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Composkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071403390_Composkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
